// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hmc5983.proto

#ifndef PROTOBUF_hmc5983_2eproto__INCLUDED
#define PROTOBUF_hmc5983_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "vector3.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_hmc5983_2eproto();
void protobuf_AssignDesc_hmc5983_2eproto();
void protobuf_ShutdownFile_hmc5983_2eproto();

class HMC5983Readings;

// ===================================================================

class HMC5983Readings : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:HMC5983Readings) */ {
 public:
  HMC5983Readings();
  virtual ~HMC5983Readings();

  HMC5983Readings(const HMC5983Readings& from);

  inline HMC5983Readings& operator=(const HMC5983Readings& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HMC5983Readings& default_instance();

  void Swap(HMC5983Readings* other);

  // implements Message ----------------------------------------------

  inline HMC5983Readings* New() const { return New(NULL); }

  HMC5983Readings* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HMC5983Readings& from);
  void MergeFrom(const HMC5983Readings& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(HMC5983Readings* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .Vector3 magnetometer = 1;
  bool has_magnetometer() const;
  void clear_magnetometer();
  static const int kMagnetometerFieldNumber = 1;
  const ::Vector3& magnetometer() const;
  ::Vector3* mutable_magnetometer();
  ::Vector3* release_magnetometer();
  void set_allocated_magnetometer(::Vector3* magnetometer);

  // required float temperature = 2;
  bool has_temperature() const;
  void clear_temperature();
  static const int kTemperatureFieldNumber = 2;
  float temperature() const;
  void set_temperature(float value);

  // required uint64 timestamp = 3;
  bool has_timestamp() const;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 3;
  ::google::protobuf::uint64 timestamp() const;
  void set_timestamp(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:HMC5983Readings)
 private:
  inline void set_has_magnetometer();
  inline void clear_has_magnetometer();
  inline void set_has_temperature();
  inline void clear_has_temperature();
  inline void set_has_timestamp();
  inline void clear_has_timestamp();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::Vector3* magnetometer_;
  ::google::protobuf::uint64 timestamp_;
  float temperature_;
  friend void  protobuf_AddDesc_hmc5983_2eproto();
  friend void protobuf_AssignDesc_hmc5983_2eproto();
  friend void protobuf_ShutdownFile_hmc5983_2eproto();

  void InitAsDefaultInstance();
  static HMC5983Readings* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// HMC5983Readings

// required .Vector3 magnetometer = 1;
inline bool HMC5983Readings::has_magnetometer() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HMC5983Readings::set_has_magnetometer() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HMC5983Readings::clear_has_magnetometer() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HMC5983Readings::clear_magnetometer() {
  if (magnetometer_ != NULL) magnetometer_->::Vector3::Clear();
  clear_has_magnetometer();
}
inline const ::Vector3& HMC5983Readings::magnetometer() const {
  // @@protoc_insertion_point(field_get:HMC5983Readings.magnetometer)
  return magnetometer_ != NULL ? *magnetometer_ : *default_instance_->magnetometer_;
}
inline ::Vector3* HMC5983Readings::mutable_magnetometer() {
  set_has_magnetometer();
  if (magnetometer_ == NULL) {
    magnetometer_ = new ::Vector3;
  }
  // @@protoc_insertion_point(field_mutable:HMC5983Readings.magnetometer)
  return magnetometer_;
}
inline ::Vector3* HMC5983Readings::release_magnetometer() {
  // @@protoc_insertion_point(field_release:HMC5983Readings.magnetometer)
  clear_has_magnetometer();
  ::Vector3* temp = magnetometer_;
  magnetometer_ = NULL;
  return temp;
}
inline void HMC5983Readings::set_allocated_magnetometer(::Vector3* magnetometer) {
  delete magnetometer_;
  magnetometer_ = magnetometer;
  if (magnetometer) {
    set_has_magnetometer();
  } else {
    clear_has_magnetometer();
  }
  // @@protoc_insertion_point(field_set_allocated:HMC5983Readings.magnetometer)
}

// required float temperature = 2;
inline bool HMC5983Readings::has_temperature() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HMC5983Readings::set_has_temperature() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HMC5983Readings::clear_has_temperature() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HMC5983Readings::clear_temperature() {
  temperature_ = 0;
  clear_has_temperature();
}
inline float HMC5983Readings::temperature() const {
  // @@protoc_insertion_point(field_get:HMC5983Readings.temperature)
  return temperature_;
}
inline void HMC5983Readings::set_temperature(float value) {
  set_has_temperature();
  temperature_ = value;
  // @@protoc_insertion_point(field_set:HMC5983Readings.temperature)
}

// required uint64 timestamp = 3;
inline bool HMC5983Readings::has_timestamp() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void HMC5983Readings::set_has_timestamp() {
  _has_bits_[0] |= 0x00000004u;
}
inline void HMC5983Readings::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void HMC5983Readings::clear_timestamp() {
  timestamp_ = GOOGLE_ULONGLONG(0);
  clear_has_timestamp();
}
inline ::google::protobuf::uint64 HMC5983Readings::timestamp() const {
  // @@protoc_insertion_point(field_get:HMC5983Readings.timestamp)
  return timestamp_;
}
inline void HMC5983Readings::set_timestamp(::google::protobuf::uint64 value) {
  set_has_timestamp();
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:HMC5983Readings.timestamp)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_hmc5983_2eproto__INCLUDED
